// Service Worker der App (Vorlage). `node tools/build_pwa.js <Ordner>` setzt VERSION und FILES ein und schreibt <Ordner>/sw.js.
// Ziel: (1) komplett offline spielbar, (2) online IMMER exakt der Stand der Webseite.
//   - Installieren: alle Dateien (FILES) werden vorab gecacht, erst wenn alle da sind, wird der neue Worker aktiv (alles oder nichts).
//   - Abrufen: erst das Netz (mit Zeitlimit), das Ergebnis wandert in den Cache; nur ohne Netz kommt der Cache dran.
//     Damit gibt es online nie einen veralteten Stand, offline den zuletzt geladenen.
//   - Neue Version: jede Aenderung an einer Datei aendert VERSION, damit auch sw.js selbst -> der Browser installiert den neuen Worker,
//     der uebernimmt sofort (skipWaiting + claim); die Seite (js/pwa.js) laedt dann im Hauptmenue neu.
// Nur gleiche Herkunft: Anfragen an Supabase (Konto) und andere Server laufen unveraendert am Worker vorbei.
const VERSION = 'ae5a063d02';
const FILES = [
  "./",
  "assets/fonts/PixelifySans.ttf",
  "assets/img_new/adrenalineIcon.png",
  "assets/img_new/aegisIcon.png",
  "assets/img_new/armorIcon.png",
  "assets/img_new/barrierIcon.png",
  "assets/img_new/beam1.png",
  "assets/img_new/beam2.png",
  "assets/img_new/beamIcon.png",
  "assets/img_new/beamLoad1.png",
  "assets/img_new/beamLoad2.png",
  "assets/img_new/berserkIcon.png",
  "assets/img_new/blackholeIcon.png",
  "assets/img_new/bladesIcon.png",
  "assets/img_new/blinkIcon.png",
  "assets/img_new/blood1.png",
  "assets/img_new/blood2.png",
  "assets/img_new/blood3.png",
  "assets/img_new/bombardIcon.png",
  "assets/img_new/bomber.png",
  "assets/img_new/boomerangIcon.png",
  "assets/img_new/bossAnim1.png",
  "assets/img_new/bossAnim10.png",
  "assets/img_new/bossAnim11.png",
  "assets/img_new/bossAnim12.png",
  "assets/img_new/bossAnim13.png",
  "assets/img_new/bossAnim14.png",
  "assets/img_new/bossAnim2.png",
  "assets/img_new/bossAnim3.png",
  "assets/img_new/bossAnim4.png",
  "assets/img_new/bossAnim5.png",
  "assets/img_new/bossAnim6.png",
  "assets/img_new/bossAnim7.png",
  "assets/img_new/bossAnim8.png",
  "assets/img_new/bossAnim9.png",
  "assets/img_new/bosshp0.png",
  "assets/img_new/bosshp1.png",
  "assets/img_new/bosshp2.png",
  "assets/img_new/bosshp3.png",
  "assets/img_new/bosshp4.png",
  "assets/img_new/bosshp5.png",
  "assets/img_new/bosshp6.png",
  "assets/img_new/bounceIcon.png",
  "assets/img_new/bubble.png",
  "assets/img_new/buffCharge.png",
  "assets/img_new/buffChrono.png",
  "assets/img_new/buffCoolant.png",
  "assets/img_new/buffGuard.png",
  "assets/img_new/buffHaste.png",
  "assets/img_new/buffMagnet.png",
  "assets/img_new/buffNova.png",
  "assets/img_new/buffPower.png",
  "assets/img_new/buffRapid.png",
  "assets/img_new/buffRegen.png",
  "assets/img_new/buffVampire.png",
  "assets/img_new/capacitorIcon.png",
  "assets/img_new/catalystIcon.png",
  "assets/img_new/chainIcon.png",
  "assets/img_new/chronoIcon.png",
  "assets/img_new/circle.png",
  "assets/img_new/clock0.png",
  "assets/img_new/clock1.png",
  "assets/img_new/clock10.png",
  "assets/img_new/clock11.png",
  "assets/img_new/clock12.png",
  "assets/img_new/clock13.png",
  "assets/img_new/clock14.png",
  "assets/img_new/clock15.png",
  "assets/img_new/clock16.png",
  "assets/img_new/clock17.png",
  "assets/img_new/clock18.png",
  "assets/img_new/clock19.png",
  "assets/img_new/clock2.png",
  "assets/img_new/clock20.png",
  "assets/img_new/clock21.png",
  "assets/img_new/clock22.png",
  "assets/img_new/clock23.png",
  "assets/img_new/clock24.png",
  "assets/img_new/clock25.png",
  "assets/img_new/clock26.png",
  "assets/img_new/clock27.png",
  "assets/img_new/clock28.png",
  "assets/img_new/clock29.png",
  "assets/img_new/clock3.png",
  "assets/img_new/clock30.png",
  "assets/img_new/clock4.png",
  "assets/img_new/clock5.png",
  "assets/img_new/clock6.png",
  "assets/img_new/clock7.png",
  "assets/img_new/clock8.png",
  "assets/img_new/clock9.png",
  "assets/img_new/damageIcon.png",
  "assets/img_new/damageOverlay.png",
  "assets/img_new/dash1.png",
  "assets/img_new/dash2.png",
  "assets/img_new/death1.png",
  "assets/img_new/death10.png",
  "assets/img_new/death11.png",
  "assets/img_new/death12.png",
  "assets/img_new/death13.png",
  "assets/img_new/death14.png",
  "assets/img_new/death15.png",
  "assets/img_new/death16.png",
  "assets/img_new/death17.png",
  "assets/img_new/death18.png",
  "assets/img_new/death19.png",
  "assets/img_new/death2.png",
  "assets/img_new/death3.png",
  "assets/img_new/death4.png",
  "assets/img_new/death5.png",
  "assets/img_new/death6.png",
  "assets/img_new/death7.png",
  "assets/img_new/death8.png",
  "assets/img_new/death9.png",
  "assets/img_new/deathSecret1.png",
  "assets/img_new/deathSecret2.png",
  "assets/img_new/deathSecret3.png",
  "assets/img_new/deathSecret4.png",
  "assets/img_new/decoyIcon.png",
  "assets/img_new/dmg1.png",
  "assets/img_new/dmg10.png",
  "assets/img_new/dmg20.png",
  "assets/img_new/dmg8.png",
  "assets/img_new/dmg9.png",
  "assets/img_new/dmgCore.png",
  "assets/img_new/dmgHeal.png",
  "assets/img_new/droneIcon.png",
  "assets/img_new/enemyShot.png",
  "assets/img_new/fieldIcon.png",
  "assets/img_new/fireIcon.png",
  "assets/img_new/fortressIcon.png",
  "assets/img_new/frostIcon.png",
  "assets/img_new/grenadeIcon.png",
  "assets/img_new/ground.png",
  "assets/img_new/ground2.png",
  "assets/img_new/ground3.png",
  "assets/img_new/ground4.png",
  "assets/img_new/guardMirror.png",
  "assets/img_new/guardPlate.png",
  "assets/img_new/hackIcon.png",
  "assets/img_new/hammerIcon.png",
  "assets/img_new/heal.png",
  "assets/img_new/heroAlchemist.png",
  "assets/img_new/heroArchon.png",
  "assets/img_new/heroBulwark.png",
  "assets/img_new/heroHarbinger.png",
  "assets/img_new/heroSpecter.png",
  "assets/img_new/hp0.png",
  "assets/img_new/hp1.png",
  "assets/img_new/hp10.png",
  "assets/img_new/hp11.png",
  "assets/img_new/hp12.png",
  "assets/img_new/hp13.png",
  "assets/img_new/hp14.png",
  "assets/img_new/hp15.png",
  "assets/img_new/hp16.png",
  "assets/img_new/hp17.png",
  "assets/img_new/hp2.png",
  "assets/img_new/hp3.png",
  "assets/img_new/hp4.png",
  "assets/img_new/hp5.png",
  "assets/img_new/hp6.png",
  "assets/img_new/hp7.png",
  "assets/img_new/hp8.png",
  "assets/img_new/hp9.png",
  "assets/img_new/impulseIcon.png",
  "assets/img_new/katanaIcon.png",
  "assets/img_new/keysettings.png",
  "assets/img_new/kite.png",
  "assets/img_new/kiteHit.png",
  "assets/img_new/lanceIcon.png",
  "assets/img_new/leech.png",
  "assets/img_new/luckyIcon.png",
  "assets/img_new/miner.png",
  "assets/img_new/missile.png",
  "assets/img_new/molotovIcon.png",
  "assets/img_new/nanoIcon.png",
  "assets/img_new/necro.png",
  "assets/img_new/necroIcon.png",
  "assets/img_new/octagon.png",
  "assets/img_new/octagonHit.png",
  "assets/img_new/overchargeIcon.png",
  "assets/img_new/overclockIcon.png",
  "assets/img_new/pauseIcon.png",
  "assets/img_new/phoenixIcon.png",
  "assets/img_new/player.png",
  "assets/img_new/pulseIcon.png",
  "assets/img_new/regenIcon.png",
  "assets/img_new/rhombus.png",
  "assets/img_new/rhombus1hp.png",
  "assets/img_new/riftIcon.png",
  "assets/img_new/rocketIcon.png",
  "assets/img_new/scannerIcon.png",
  "assets/img_new/shockstepIcon.png",
  "assets/img_new/shot.png",
  "assets/img_new/shotgunIcon.png",
  "assets/img_new/slotEmptyIcon.png",
  "assets/img_new/sniper.png",
  "assets/img_new/spawnPoint.png",
  "assets/img_new/spawner.png",
  "assets/img_new/spawnerHit.png",
  "assets/img_new/splitter.png",
  "assets/img_new/square.png",
  "assets/img_new/square1hp.png",
  "assets/img_new/startscreen.png",
  "assets/img_new/stimIcon.png",
  "assets/img_new/stormIcon.png",
  "assets/img_new/summoner.png",
  "assets/img_new/summonerHit.png",
  "assets/img_new/support.png",
  "assets/img_new/surgeIcon.png",
  "assets/img_new/swapIcon.png",
  "assets/img_new/sword.png",
  "assets/img_new/tank.png",
  "assets/img_new/teleporter.png",
  "assets/img_new/thornsIcon.png",
  "assets/img_new/thrustersIcon.png",
  "assets/img_new/triangle.png",
  "assets/img_new/turret.png",
  "assets/img_new/turretHit.png",
  "assets/img_new/ult1.png",
  "assets/img_new/ult2.png",
  "assets/img_new/ult3.png",
  "assets/img_new/ult4.png",
  "assets/img_new/ultFlash.png",
  "assets/img_new/ultIcon.png",
  "assets/img_new/vampireIcon.png",
  "assets/img_new/wave1.png",
  "assets/img_new/wave2.png",
  "assets/img_new/wave3.png",
  "assets/img_new/wave4.png",
  "assets/img_new/whipIcon.png",
  "icons/icon-180.png",
  "icons/icon-192.png",
  "icons/icon-512.png",
  "index.html",
  "js/account.js",
  "js/achievements.js",
  "js/arsenal.js",
  "js/art_manifest.js",
  "js/assets.js",
  "js/bosses.js",
  "js/config.js",
  "js/cosmetics.js",
  "js/cosmetics2.js",
  "js/deathtexts.js",
  "js/director.js",
  "js/elites.js",
  "js/enemies.js",
  "js/game.js",
  "js/heroes.js",
  "js/i18n.js",
  "js/i18n_de.js",
  "js/i18n_de2.js",
  "js/i18n_de3.js",
  "js/input.js",
  "js/juice.js",
  "js/mapenv.js",
  "js/mapfx.js",
  "js/mapspecial.js",
  "js/meteors.js",
  "js/milestonefx.js",
  "js/music.js",
  "js/nipplejs.min.js",
  "js/obstacles.js",
  "js/patterns.js",
  "js/player.js",
  "js/pwa.js",
  "js/runstats.js",
  "js/safespot.js",
  "js/save.js",
  "js/sfx.js",
  "js/statsscreen.js",
  "js/style.js",
  "js/touch.js",
  "js/transfer.js",
  "js/tutorial.js",
  "js/ui.js",
  "js/util.js",
  "js/weapons.js",
  "js/xp.js",
  "manifest.webmanifest"
];
const CACHE = 'deatharena-' + VERSION;
const NET_TIMEOUT = 4000;

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(FILES.map((f) => new Request(f, { cache: 'reload' })))).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (e) => {
  e.waitUntil(caches.keys().then((ks) => Promise.all(ks.filter((k) => k.startsWith('deatharena-') && k !== CACHE).map((k) => caches.delete(k)))).then(() => self.clients.claim()));
});

async function networkFirst(req) {
  const cache = await caches.open(CACHE);
  try {
    const ctrl = new AbortController(), t = setTimeout(() => ctrl.abort(), NET_TIMEOUT);
    const res = await fetch(req, { signal: ctrl.signal, cache: 'no-cache' });
    clearTimeout(t);
    if (res.ok && res.type === 'basic') cache.put(req, res.clone());
    return res;
  } catch (err) {
    const hit = (await cache.match(req, { ignoreSearch: true })) || (req.mode === 'navigate' ? await cache.match(new URL('index.html', self.registration.scope).href) : null);
    if (hit) return hit;
    throw err;
  }
}

self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET') return;
  if (new URL(req.url).origin !== self.location.origin) return;
  e.respondWith(networkFirst(req));
});
